# Generated by Django 5.0.6 on 2024-06-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "ifsc",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("branch", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=195)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=26)),
                ("bank_name", models.CharField(max_length=49)),
                (
                    "bank_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.bank"
                    ),
                ),
            ],
        ),
    ]
